SEARDUINO_PATH = /opt/searduino
PROG = propelsion
SRC_C = propelsion.c main.c
ARDUINO = stub
SHLIB = propelsion.so
include $(SEARDUINO_PATH)/share/searduino/mk/searduino.mk

SEARDUINO_PATH = /opt/searduino
PROG = propelsion
SRC_C = propelsion.c ../tests/check_propelsion.c
ARDUINO = stub
USER_LD_FLAGS=-lcheck
SHLIB = propelsion.so
include $(SEARDUINO_PATH)/share/searduino/mk/searduino.mk
