SEARDUINO_PATH=/opt/searduino
PROG=main
SRC_C=hovering_motor.c hovering_control.c main.c
SHLIB=hovering_motor.so
ARDUINO=stub
USER_C_FLAGS=-DSTUB_TEST
include $(SEARDUINO_PATH)/share/searduino/mk/searduino.mk
