SEARDUINO_PATH = /opt/searduino

# Add your source files here
SRC_C=
SRC_CXX= WiFlySerial.cpp
MAIN_SRC = 
ARDUINO = mega2560

LIB = libwifly.a
LIB_H = Streaming.h WiFlySerial.h
USER_LIB_INSTALL_PATH = ../../../../3pp/bin

export SRC_FILES= $(SRC_C) $(SRC_CXX)

include $(SEARDUINO_PATH)/share/searduino/mk/searduino.mk
