## Process this file with automake to produce Makefile.in

TESTS = connection, set_value, get_value, disconnection
check_PROGRAMS = check_hc_remote
check_money_SOURCES = check_hc_remote.c $(hovercraft)/src/computer/hcraft_remote_api.h
check_money_CFLAGS = @CHECK_CFLAGS@

