// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hoveritu.domain;

import com.hoveritu.domain.HovercraftState;
import com.hoveritu.domain.HovercraftStateDataOnDemand;
import com.hoveritu.domain.HovercraftStateIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HovercraftStateIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HovercraftStateIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HovercraftStateIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: HovercraftStateIntegrationTest: @Transactional;
    
    @Autowired
    private HovercraftStateDataOnDemand HovercraftStateIntegrationTest.dod;
    
    @Test
    public void HovercraftStateIntegrationTest.testCountHovercraftStates() {
        Assert.assertNotNull("Data on demand for 'HovercraftState' failed to initialize correctly", dod.getRandomHovercraftState());
        long count = HovercraftState.countHovercraftStates();
        Assert.assertTrue("Counter for 'HovercraftState' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HovercraftStateIntegrationTest.testFindHovercraftState() {
        HovercraftState obj = dod.getRandomHovercraftState();
        Assert.assertNotNull("Data on demand for 'HovercraftState' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HovercraftState' failed to provide an identifier", id);
        obj = HovercraftState.findHovercraftState(id);
        Assert.assertNotNull("Find method for 'HovercraftState' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'HovercraftState' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HovercraftStateIntegrationTest.testFindAllHovercraftStates() {
        Assert.assertNotNull("Data on demand for 'HovercraftState' failed to initialize correctly", dod.getRandomHovercraftState());
        long count = HovercraftState.countHovercraftStates();
        Assert.assertTrue("Too expensive to perform a find all test for 'HovercraftState', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<HovercraftState> result = HovercraftState.findAllHovercraftStates();
        Assert.assertNotNull("Find all method for 'HovercraftState' illegally returned null", result);
        Assert.assertTrue("Find all method for 'HovercraftState' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HovercraftStateIntegrationTest.testFindHovercraftStateEntries() {
        Assert.assertNotNull("Data on demand for 'HovercraftState' failed to initialize correctly", dod.getRandomHovercraftState());
        long count = HovercraftState.countHovercraftStates();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<HovercraftState> result = HovercraftState.findHovercraftStateEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'HovercraftState' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'HovercraftState' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HovercraftStateIntegrationTest.testFlush() {
        HovercraftState obj = dod.getRandomHovercraftState();
        Assert.assertNotNull("Data on demand for 'HovercraftState' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HovercraftState' failed to provide an identifier", id);
        obj = HovercraftState.findHovercraftState(id);
        Assert.assertNotNull("Find method for 'HovercraftState' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyHovercraftState(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'HovercraftState' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HovercraftStateIntegrationTest.testMergeUpdate() {
        HovercraftState obj = dod.getRandomHovercraftState();
        Assert.assertNotNull("Data on demand for 'HovercraftState' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HovercraftState' failed to provide an identifier", id);
        obj = HovercraftState.findHovercraftState(id);
        boolean modified =  dod.modifyHovercraftState(obj);
        Integer currentVersion = obj.getVersion();
        HovercraftState merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'HovercraftState' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HovercraftStateIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'HovercraftState' failed to initialize correctly", dod.getRandomHovercraftState());
        HovercraftState obj = dod.getNewTransientHovercraftState(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'HovercraftState' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'HovercraftState' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'HovercraftState' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HovercraftStateIntegrationTest.testRemove() {
        HovercraftState obj = dod.getRandomHovercraftState();
        Assert.assertNotNull("Data on demand for 'HovercraftState' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HovercraftState' failed to provide an identifier", id);
        obj = HovercraftState.findHovercraftState(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'HovercraftState' with identifier '" + id + "'", HovercraftState.findHovercraftState(id));
    }
    
}
