TEST_DIR=test/
SEARDUINO_PATH = /opt/searduino
PROG = Bluetooth

# Add your source files here
SRC_C = 
SRC_CXX = main.c messageHandler.c bluetooth_command.c bluetooth_controler.c serial_interface.cpp
ARDUINO = stub
SHLIB = Bluetooth.so
include $(SEARDUINO_PATH)/share/searduino/mk/searduino.mk

