TEST_DIR=test/
SEARDUINO_PATH = /opt/searduino
PROG = Bluetooth

# Add your source files here
SRC_C = main.c messageHandler.c initTimerInterrupt.c bluetooth_command.c bluetooth_controler.c
SRC_CXX = serial_interface.cpp
ARDUINO = stub
SHLIB = Bluetooth.so
include $(SEARDUINO_PATH)/share/searduino/mk/searduino.mk

